apiVersion : apps/v1
kind: Deployment
metadata:
  name: httpd-frontend

spec:
  replicas: 3
  strategy:
    rollingUpdate:

  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      name: nginx-pod
      labels:
        app: nginx
    spec:
      containers:
        - name: httpd:2.4-alpine
          image: nginx